export type OnboardingStepKey =
  | "personel"
  | "atolye_gideri"
  | "makine_maliyeti"
  | "musteri"
  | "ilk_teklif"
  | "is_programi"
  | "tahsilat";

export type OnboardingPageTourStep = {
  key: string;
  target: string;
  title: string;
  copy: string;
  value: string;
  actionLabel?: string;
};

export type OnboardingStep = {
  key: OnboardingStepKey;
  title: string;
  shortDescription: string;
  wowCopy: string;
  coachmarkTitle: string;
  coachmarkCopy: string;
  pageGuide: {
    title: string;
    promise: string;
    why: string;
    bullets: string[];
    outcome: string;
  };
  pageTourSteps?: OnboardingPageTourStep[];
  href: string;
  target: string;
  icon: string;
  order: number;
  placement: "right" | "bottom" | "top";
  desktopOnly?: boolean;
};

export const onboardingSteps: OnboardingStep[] = [
  {
    key: "personel",
    title: "Ekibini tanıt",
    shortDescription: "İşi kişilere, sorumluluğu veriye bağla.",
    wowCopy: "Personel maliyeti olmadan teklif karı tahmindir. Metrix hız, sorumluluk ve maliyeti görünür yapar.",
    coachmarkTitle: "Ekibini sisteme tanıt.",
    coachmarkCopy: "Metrix işi kişilere bağlasın; kim hangi işi ne hızda yapıyor gör.",
    pageGuide: {
      title: "Önce ekibini tanıt.",
      promise: "Metrix işi kişilere bağlar; hız, sorumluluk ve maliyet görünür olur.",
      why: "Personel maliyeti olmadan teklif karı tahmindir. Metrix bu veriyi işçilik yükünü gerçek fiyatlara yansıtmak için kullanır.",
      bullets: ["Personel ekle", "Görev/rol seç", "Maliyet bilgisini gir"],
      outcome: "Bundan sonra tekliflerde ve iş programında gerçek işçilik yükünü okumaya başlarsın.",
    },
    pageTourSteps: [
      {
        key: "personel-create",
        target: "personel-create",
        title: "Önce ekibini tanıtıyoruz.",
        copy: "Personel ekle butonuyla ilk kişiyi sisteme al.",
        value: "Çünkü Metrix işi kişilere bağlayacak; hız, sorumluluk ve maliyet görünür olacak.",
        actionLabel: "Personel ekle",
      },
      {
        key: "personel-name",
        target: "personel-name",
        title: "Ad soyad ile operasyon kimliğini oluştur.",
        copy: "Bu kişi artık sadece bir kayıt değil, Metrix içinde işi üstlenen gerçek operasyon kullanıcısı olacak.",
        value: "Metrix görevleri, performansı ve sorumluluğu bu kişi üzerinden okuyacak.",
      },
      {
        key: "personel-phone",
        target: "personel-phone",
        title: "Telefon bilgisini ekle.",
        copy: "Saha, atölye ve ofis arasındaki temas bilgisini tek personel kartında tut.",
        value: "Operasyon aksiyonları kişiye bağlandığında ekip iletişimi dağınık kalmaz.",
      },
      {
        key: "personel-email",
        target: "personel-email",
        title: "E-posta bilgisini gir.",
        copy: "E-posta, personelin dijital kimliğini ve giriş hesabını tamamlayan temel bilgidir.",
        value: "Metrix ileride bildirim, erişim ve kullanıcı ayrımını bu kimlik üzerinden güçlendirebilir.",
      },
      {
        key: "personel-password",
        target: "personel-password",
        title: "Giriş bilgisini belirle.",
        copy: "Bu kişiye sadece personel kaydı açmıyoruz; Metrix içinde kontrollü erişim veriyoruz.",
        value: "Şifreyle personel kendi operasyon ekranına girip yetkisi kadar işlem yapabilir.",
      },
      {
        key: "personel-manager",
        target: "personel-manager",
        title: "Kime bağlı olduğunu seç.",
        copy: "Usta, kalfa, ekip veya ofis ilişkisini tanımla.",
        value: "Metrix sorumluluk zincirini görür; iş sadece kişiye değil ekip yapısına da bağlanır.",
      },
      {
        key: "personel-role-group",
        target: "personel-role-group",
        title: "Rol grubunu seç.",
        copy: "Ölçü, kesim, toplama, montaj veya ofis gibi ana operasyon rolünü netleştir.",
        value: "Metrix iş programında kapasiteyi ve sorumluluğu operasyon rolüne göre okumaya başlar.",
      },
      {
        key: "personel-role",
        target: "personel-role",
        title: "Görevini seç.",
        copy: "Bu kişinin ölçü, kesim, toplama veya montaj tarafındaki rolünü netleştir.",
        value: "Metrix iş programında kimin hangi operasyonu taşıyacağını buradan anlayacak.",
      },
      {
        key: "personel-seniority",
        target: "personel-seniority",
        title: "Kıdem bilgisini gir.",
        copy: "Çalışma yılı, ekip içindeki deneyim ve sorumluluk seviyesini anlamaya yardım eder.",
        value: "Performans ve atama değerlendirmelerinde tecrübeyi görünür kılarsın.",
      },
      {
        key: "personel-cost",
        target: "personel-cost",
        title: "Maliyet bilgisini gir.",
        copy: "Maaş ve çalışma düzeni işçilik maliyetinin temelidir.",
        value: "Personel maliyeti olmadan teklif karı tahmindir. Metrix bu veriyi işçilik yükünü gerçek fiyata yansıtmak için kullanır.",
      },
      {
        key: "personel-sgk",
        target: "personel-sgk",
        title: "SGK ve ek maliyeti netleştir.",
        copy: "Maaş tek başına gerçek maliyet değildir; işveren yükü fiyat motorunu etkiler.",
        value: "Metrix işçilik maliyetini eksik değil, gerçek atölye yüküyle hesaplar.",
      },
      {
        key: "personel-work-days",
        target: "personel-work-days",
        title: "Çalışma düzenini gir.",
        copy: "Haftalık çalışma günü kapasite hesabının temelidir.",
        value: "Metrix iş programında ekip kapasitesini daha doğru okumaya başlar.",
      },
      {
        key: "personel-form-save",
        target: "personel-form-save",
        title: "Personel kaydını oluştur.",
        copy: "Şimdi bu kişiyi Metrix operasyon hafızasına ekle.",
        value: "Artık bu kişi iş programında atanabilir, performansı ölçülebilir ve işçilik maliyeti tekliflere yansır.",
        actionLabel: "Kaydet",
      },
      {
        key: "personel-permissions-tab",
        target: "personel-permissions-tab",
        title: "Yetkiler sekmesine geç.",
        copy: "Bu kişiye sadece personel kaydı açmıyoruz; hangi ekranları görebileceğini ve hangi işlemleri yapabileceğini belirliyoruz.",
        value: "Operasyon kontrolü burada başlar: herkes sadece ihtiyacı olan alanı görür.",
        actionLabel: "Yetkilere geç",
      },
      {
        key: "personel-permission-dashboard",
        target: "personel-permission-dashboard",
        title: "Genel görünüm erişimini düşün.",
        copy: "Dashboard yetkisiyle personel genel operasyon görünümüne erişebilir.",
        value: "Ekip aynı operasyon akışını görür; bilgi kişilerin hafızasında kalmaz.",
      },
      {
        key: "personel-permission-isler",
        target: "personel-permission-isler",
        title: "İşler ve teklif erişimini belirle.",
        copy: "İşler yetkisi, teklif ve operasyon kayıtlarına erişimi belirler.",
        value: "Satış ve operasyon bilgisini sadece doğru kişilere açarsın.",
      },
      {
        key: "personel-permission-is-programi",
        target: "personel-permission-is-programi",
        title: "İş programı erişimini aç.",
        copy: "İş programı yetkisiyle personel ölçü, imalat ve montaj görevlerini takip edebilir.",
        value: "Metrix görevleri kişiye bağlar; herkes kendi operasyon akışını net görür.",
      },
      {
        key: "personel-permission-production",
        target: "personel-permission-production",
        title: "İmalat tamamlama yetkisini yönet.",
        copy: "Bu yetki, sahadaki veya atölyedeki işi tamamlandı olarak işaretleme gücü verir.",
        value: "Operasyon ilerlemesi doğru kişiden geldiğinde performans ölçümü güvenilir olur.",
      },
      {
        key: "personel-permission-tahsilat",
        target: "personel-permission-tahsilat",
        title: "Finansal görünürlüğü sınırla.",
        copy: "Tahsilat ve maliyet bilgisi finansal veri içerir. Bu alanı sadece yetkili kişilere aç.",
        value: "Nakit akışı ve maliyet bilgisi operasyonun içinde kalır ama herkesin önüne düşmez.",
      },
      {
        key: "personel-permission-personel",
        target: "personel-permission-personel",
        title: "Personel erişimini yöneticide tut.",
        copy: "Personel yetkisi sadece yöneticiler için açılmalı. Ekip bilgilerini herkes görmemeli.",
        value: "Metrix ekip bilgisini operasyon için kullanır; erişimi kontrollü tutmak yönetim kalitesini korur.",
      },
      {
        key: "personel-permission-atolye",
        target: "personel-permission-atolye",
        title: "Atölye ayarlarını yöneticide tut.",
        copy: "Atölye maliyetleri fiyat motorunu etkiler. Bu alan yöneticilerde kalmalı.",
        value: "Metrix'in fiyat ve operasyon zekasını etkileyen ayarlar kontrollü kalır.",
      },
      {
        key: "personel-save",
        target: "personel-save",
        title: "Yetkileri kaydet.",
        copy: "Bu kişinin Metrix içinde nerede duracağını, ne göreceğini ve ne yapacağını netleştir.",
        value: "Artık personel sadece kaydedilmiş biri değil; operasyonun kontrollü bir kullanıcısı.",
        actionLabel: "Yetkileri kaydet",
      },
    ],
    href: "/dashboard/personel",
    target: "personel",
    icon: "👥",
    order: 1,
    placement: "right",
  },
  {
    key: "atolye_gideri",
    title: "Atölye yükünü kur",
    shortDescription: "Görünmeyen giderleri teklif motoruna bağla.",
    wowCopy: "Kira, elektrik ve maaş gibi yükleri tanıt. Fiyat artık hisle değil veriyle oluşsun.",
    coachmarkTitle: "Gerçek atölye maliyetini kur.",
    coachmarkCopy: "Teklif verirken tahmini değil gerçek karı gör.",
    pageGuide: {
      title: "Atölye yükünü sisteme tanıt.",
      promise: "Metrix teklif verirken görünmeyen sabit giderleri de hesaba katar.",
      why: "Kira, elektrik, maaş ve benzeri yükler fiyatın içinde yoksa gerçek kar görünmez.",
      bullets: ["Sabit giderleri gir", "Personel yükünü kontrol et", "Dakika maliyetini netleştir"],
      outcome: "Atölye maliyet motoru aktif. Teklifler artık tahmin değil gerçek maliyet zemini üzerinde oluşuyor.",
    },
    pageTourSteps: [
      {
        key: "atolye-gider-tab",
        target: "atolye-gider-tab",
        title: "Gider formunu açıyoruz.",
        copy: "Giderler bölümünü seç: kira, elektrik ve personel yükünü Metrix'e tanıt.",
        value: "Bu veriler olmadan teklif fiyatı gerçek maliyeti görmez — kar tahminden ibaret kalır.",
        actionLabel: "Giderlere geç",
      },
      {
        key: "atolye-personelden-aktar",
        target: "atolye-personelden-aktar",
        title: "Az önce girdiğin personel verileri burada seni bekliyor.",
        copy: "Personel modülünde kaydettiğin maaş ve SGK bilgileri atölye giderlerine otomatik aktarılabilir.",
        value: "Metrix aynı veriyi tekrar yazdırmaz; operasyon katmanlarını birbirine bağlar.",
        actionLabel: "Kayıtlardan aktar",
      },
      {
        key: "atolye-toplamMaas",
        target: "atolye-toplamMaas",
        title: "En büyük kalemi fiyata bağla.",
        copy: "Aylık toplam maaş atölyenin en ağır sabit yüküdür. Girince sağ paneldeki dakika maliyetinin değiştiğini gör.",
        value: "Bu olmadan teklif karı hayaldir. Metrix işçilik yükünü gerçek fiyata buradan yansıtır.",
      },
      {
        key: "atolye-sgkGideri",
        target: "atolye-sgkGideri",
        title: "Gerçek işçilik yükü maaştan büyük.",
        copy: "SGK işveren payı maaşın üstüne gelen zorunlu maliyet. Girdikçe aylık gider canlı güncelleniyor.",
        value: "Maaş + SGK = gerçek işçilik. Metrix ikisini ayrı okur, teklife birlikte yansıtır.",
      },
      {
        key: "atolye-kira",
        target: "atolye-kira",
        title: "Sabit giderleri sisteme tanıt.",
        copy: "Kira üretim olsun olmasın her ay gelir; fiyatın içinde olmalı.",
        value: "Metrix sabit gider + personel yükü + makine amortismanını toplar; plaka başına maliyet çıkar.",
      },
      {
        key: "atolye-elektrik",
        target: "atolye-elektrik",
        title: "Üretim enerji maliyetini göster.",
        copy: "Kesim, CNC, aydınlatma — elektrik sessiz ama büyük üretim ortağıdır. Girince enerji maliyeti fiyat motoruna ekleniyor.",
        value: "Aylık elektrik gideri dakika maliyetini doğrudan etkiler; teklif motoruna girmeli.",
      },
      {
        key: "atolye-kapasite-tab",
        target: "atolye-kapasite-tab",
        title: "Son adım: üretim kapasiteni tanımla.",
        copy: "Metrix giderleri toplamaz; üretim kapasitesine böler. Kapasite bölümüne geç.",
        value: "Dakika maliyeti = Toplam gider ÷ Aylık üretim kapasitesi. Teklif motoru bunu kullanır.",
        actionLabel: "Kapasiteye geç",
      },
      {
        key: "atolye-aylikPorselenPlaka",
        target: "atolye-aylikPorselenPlaka",
        title: "Kapasiteni söyle — dakika maliyeti hesaplanabilsin.",
        copy: "Aylık ürettiğin plaka sayısı toplam gideri plataya böler. Girdikçe dakika maliyeti ve verimlilik skoru canlı güncelleniyor.",
        value: "Plaka kapasitesi + toplam gider = dakikalık maliyet. Yeşil \"Verimli\" badge'ini hedefle.",
      },
      {
        key: "atolye-kaydet",
        target: "atolye-kaydet",
        title: "Metrix maliyet motorunu aktive et.",
        copy: "Bu bilgileri kaydet; Metrix artık tahmin değil gerçek maliyet zeminiyle fiyat üretecek.",
        value: "İlk kayıttan sonra tekliflerde atölyenin gerçek dakika maliyeti fiyat motoruna girer.",
        actionLabel: "Kaydet",
      },
    ],
    href: "/dashboard/atolye",
    target: "atolye-gideri",
    icon: "⌁",
    order: 2,
    placement: "right",
  },
  {
    key: "makine_maliyeti",
    title: "Operasyon maliyetini ekle",
    shortDescription: "Kesimden montaja üretim dakikasını fiyatlandır.",
    wowCopy: "Kesim, pahlama, yapıştırma ve montajı gerçek üretim maliyetine bağla. Göz kararı fiyat dönemi bitsin.",
    coachmarkTitle: "Makine ve operasyon maliyetini netleştir.",
    coachmarkCopy: "Dakika maliyeti teklif motorunu gerçek üretim verisiyle besler.",
    pageGuide: {
      title: "Operasyon maliyetini görünür yap.",
      promise: "Metrix üretim dakikasını fiyata bağlar; kesim, pahlama, yapıştırma ve montaj ayrı ayrı okunur.",
      why: "Operasyon maliyeti ölçülmezse teklif sadece malzeme + tahmin olur.",
      bullets: ["Makine veya operasyon ekle", "Amortisman ve çalışma saatini gir", "Dakikalık maliyeti kontrol et"],
      outcome: "Teklif motoru artık üretimin gerçek yükünü hesaba katmaya başlar.",
    },
    href: "/dashboard/atolye",
    target: "atolye-gideri",
    icon: "⚙",
    order: 3,
    placement: "right",
  },
  {
    key: "musteri",
    title: "Müşteri hafızanı kur",
    shortDescription: "WhatsApp ve Excel dağınıklığını tek müşteri kartında topla.",
    wowCopy: "Teklif, iş programı, tahsilat ve bakiye aynı müşteri kartında birleşsin.",
    coachmarkTitle: "İlk müşterini ekle.",
    coachmarkCopy: "Satış geçmişi, bakiye ve takip aksiyonları tek müşteri hafızasında toplansın.",
    pageGuide: {
      title: "Müşteri ağını Metrix'e taşı.",
      promise: "WhatsApp'ta ve Excel'de dağınık duran müşteri geçmişi operasyon hafızasına dönüşür.",
      why: "Teklif, iş programı, tahsilat ve bakiye aynı müşteri üzerinde birleştiğinde satış takibi kaybolmaz.",
      bullets: ["Müşteri kartı oluştur", "Telefon ve cari bilgisini ekle", "Excel aktarımına hazır ol"],
      outcome: "Müşteri hafızası kuruldu. Teklif, tahsilat, bakiye ve ekstre artık tek müşteri kartında toplanıyor.",
    },
    pageTourSteps: [
      {
        key: "musteri-yeni-btn",
        target: "musteri-yeni-btn",
        title: "İlk müşteri kartını oluşturalım.",
        copy: "Müşterini WhatsApp'a değil Metrix'e tanıt. Telefon, tip ve cari bilgisi tek kart üzerinde toplanır.",
        value: "Müşteri kaydı tutmak değil, müşteri hafızası oluşturmak. Teklif, iş, tahsilat — hepsi bu kartın altında birikecek.",
        actionLabel: "Yeni Müşteri",
      },
      {
        key: "musteri-firmaAdi",
        target: "musteri-firmaAdi",
        title: "Firma adını gir.",
        copy: "Firma adı tüm teklif, ekstre ve bildirimlerde bu isimle anılacak. Bireysel müşteri için ad soyad yeterli.",
        value: "Metrix bu ismi teklif PDF'te, WhatsApp mesajında ve cari ekstre başlığında kullanır.",
      },
      {
        key: "musteri-telefon",
        target: "musteri-telefon",
        title: "Telefonu kaydet — WhatsApp aksiyona dönüşsün.",
        copy: "Metrix telefon numarasını teklif onayı, vade hatırlatması ve ekstre gönderimi için kullanır.",
        value: "Numara kayıtlıysa teklifi veya ekstreyi tek tıkla WhatsApp'tan gönderebilirsin.",
      },
      {
        key: "musteri-musteriTipi",
        target: "musteri-musteriTipi",
        title: "Müşteri tipini doğru seç.",
        copy: "Bayi, mimar, son kullanıcı veya müteahhit — her tip farklı satış davranışı ve öncelik anlamına gelir.",
        value: "Metrix müşteri tipini analiz ve segmentasyon için kullanır. Bayi ve mimar ilişkileri ayrı yönetilmeli.",
      },
      {
        key: "musteri-kaydet",
        target: "musteri-kaydet",
        title: "Müşteri kartını oluştur.",
        copy: "Bu müşteri artık Metrix hafızasında. Teklif oluşturabilir, tahsilat kaydedebilir, ekstre çıkarabilirsin.",
        value: "Müşteri kartı oluşturulduktan sonra geçmiş cari bakiyeni açılış bakiyesiyle taşıyabilirsin.",
        actionLabel: "Müşteri Oluştur",
      },
      {
        key: "musteri-sablon",
        target: "musteri-sablon",
        title: "Excel şablonunu indir.",
        copy: "Metrix'in standart şablonunu indir, mevcut müşteri listen varsa bu forma doldur.",
        value: "Şablon: Firma Adı, Telefon, E-posta, Müşteri Tipi, Açılış Bakiyesi. Bir kez doldur, toplu yükle.",
      },
      {
        key: "musteri-import",
        target: "musteri-import",
        title: "Müşteri ağını Metrix'e taşı.",
        copy: "Excel'deki müşteri listeni seç ve yükle. Metrix saniyeler içinde tüm kayıtları sisteme alır.",
        value: "WhatsApp'ta ve Excel'de dağınık duran müşteri ağın — tek tıkla Metrix'in operasyon hafızasına dönüşür.",
        actionLabel: "Excel Yükle",
      },
    ],
    href: "/dashboard/musteriler",
    target: "musteriler",
    icon: "◇",
    order: 4,
    placement: "right",
  },
  {
    key: "ilk_teklif",
    title: "İlk işi ve teklifi oluştur",
    shortDescription: "Gerçek operasyonu teklif motoruna bağla.",
    wowCopy: "Metrix sadece fiyat çıkarmaz; personel, maliyet, müşteri, taş ve operasyon bilgilerini tek teklif motorunda birleştirir.",
    coachmarkTitle: "İlk teklifini oluştur.",
    coachmarkCopy: "Teklifi WhatsApp'tan gönder; Metrix müşterinin ilgisini canlı takip etsin.",
    pageGuide: {
      title: "İlk işini oluştur.",
      promise: "Metrix fiyat yazmaz; gerçek operasyonu teklife bağlar.",
      why: "Müşteri, taş, ölçü, işçilik, operasyon ve kar aynı akışta birleştiğinde teklif gerçek üretimi temsil eder.",
      bullets: ["Müşteri seç", "Ölçü ve malzemeyi gir", "Operasyonları ve karı kontrol et"],
      outcome: "Teklif hazır, fiyat motoru çalışıyor. Plaka maliyeti, işçilik yükü ve atölye gideri artık tek hesapta birleşiyor. WhatsApp'tan gönder.",
    },
    pageTourSteps: [
      {
        key: "yeni-is-musteri-input",
        target: "yeni-is-musteri-input",
        title: "Müşteriyi teklif motoruna bağla.",
        copy: "Mevcut müşterini listeden seç — teklif, tahsilat ve bakiye otomatik o karta bağlanacak.",
        value: "İsim yazınca arama açılır. Yeni müşteriyse 'yeni olarak kullan' seçeneğiyle anında kart oluşturabilirsin.",
      },
      {
        key: "yeni-is-urun-adi",
        target: "yeni-is-urun-adi",
        title: "Taşı tanımla.",
        copy: "Calacatta Gold, Laminam Fokos, Silestone — ürün adı teklif PDF'inde ve iş kaydında görünür.",
        value: "Metrix bu bilgiyi teklif belgesine, müşteri kartına ve operasyon geçmişine işler.",
      },
      {
        key: "yeni-is-plaka-euro",
        target: "yeni-is-plaka-euro",
        title: "Plaka fiyatını gir.",
        copy: "Euro fiyatı ve kuru gir — Metrix toplam plaka maliyetini ve kaç plaka gerektiğini canlı hesaplar.",
        value: "Bu giriş olmadan maliyet hesabı gerçek değil. Plaka + işçilik + atölye yükü burada birleşiyor.",
      },
      {
        key: "yeni-is-plaka-hesapla",
        target: "yeni-is-plaka-hesapla",
        title: "Kaç plaka lazım, fire oranı ne — şimdi gör.",
        copy: "Parça ölçülerine göre plaka sayısı ve fire oranı hesaplanıyor. Bu olmadan teklif fiyatı tahmindir.",
        value: "Metrix her parçayı plakaya otomatik yerleştiriyor. Fire oranı direkt malzeme maliyetini etkiler.",
        actionLabel: "Plaka Hesapla",
      },
      {
        key: "yeni-is-gorsel-planlayici",
        target: "yeni-is-gorsel-planlayici",
        title: "Bu sistem üretimi düşünüyor.",
        copy: "Görsel Planlayıcı'yı aç: parçalar plakaya otomatik yerleşiyor, damar yönünü görebiliyorsun, sürükle-bırak ile fire'ı azaltabiliyorsun.",
        value: "Bu sadece teklif programı değil — gerçek üretimi kesimden önce simüle eden bir operasyon sistemi.",
        actionLabel: "Görsel Planlayıcı",
      },
      {
        key: "yeni-is-carpan",
        target: "yeni-is-carpan",
        title: "Fiyat motoru canlı çalışıyor.",
        copy: "Çarpana bas — fiyatın canlı değiştiğini gör. Metrix plaka maliyetini, personel yükünü ve atölye giderini biliyor.",
        value: "Artık tahminle değil gerçek maliyet zemininde fiyat veriyorsun. Çarpan yükseldikçe kâr marjı görünür.",
      },
      {
        key: "yeni-is-kaydet",
        target: "yeni-is-kaydet",
        title: "Teklif hazır — WhatsApp'ta bir tık.",
        copy: "Kaydet: teklif numaralı, kâr analizli, PDF çıktılı. Ardından müşteriye tek tıkla WhatsApp'tan gönderebilirsin.",
        value: "Müşteri teklif linkini açıp onaylayabilir. Onay gelince Metrix operasyonu başlatmaya hazır.",
        actionLabel: "Teklifi Kaydet",
      },
    ],
    href: "/dashboard/yeni-is-v3?fresh=1",
    target: "yeni-is",
    icon: "✦",
    order: 5,
    placement: "right",
  },
  {
    key: "is_programi",
    title: "Üretim kapasitesini yönet",
    shortDescription: "İş programı sadece takvim değil, canlı üretim haritasıdır.",
    wowCopy: "Metrix iş planı yazmaz; atölyenin gerçek üretim kapasitesini ölçer.",
    coachmarkTitle: "İşi programa al.",
    coachmarkCopy: "Ölçü, imalat ve montaj fazları canlı plana bağlansın.",
    pageGuide: {
      title: "İşi canlı operasyon zincirine bağla.",
      promise: "Ölçü, imalat, kesim, toplama ve montaj fazları takvimden çıkar; performans verisine dönüşür.",
      why: "Hedef süre, planlanan süre ve gerçekleşen süre karşılaştırılmadan darboğaz görünmez.",
      bullets: ["Fazları planla", "Personel ata", "Hedef ve gerçekleşen süreyi takip et"],
      outcome: "Operasyon canlıya alındı. Ölçü, imalat ve montaj fazları ekip takviminde görünüyor. Personel bildirim aldı — gecikme ve süre takibi başladı. Metrix artık bu işi teklif olarak değil, aktif operasyon olarak yönetiyor.",
    },
    pageTourSteps: [
      {
        key: "is-programi-ekle",
        target: "is-programi-ekle",
        title: "Onaylı işi üretime al.",
        copy: "Teklifi müşteri onayladı; şimdi Ölçü, İmalat ve Montaj fazlarını takvime bağlıyoruz.",
        value: "İş programa alındığında Metrix fazları planlar, personel atar ve gecikme takibini başlatır.",
        actionLabel: "Program Ekle",
      },
      {
        key: "is-programi-is-sec",
        target: "is-programi-is-sec",
        title: "Üretime alınacak işi seç.",
        copy: "Onaylı teklifler bu listede. Birini seç — AI motor ölçü, imalat ve montaj için en uygun günleri önersin.",
        value: "Metrix personel kapasitesini ve mevcut iş yükünü okuyarak boş slot bulur.",
      },
      {
        key: "is-programi-programa-al",
        target: "is-programi-programa-al",
        title: "AI planını onayla.",
        copy: "Ölçü, imalat ve montaj tarihleri hazır. İstersen değiştir, istersen direkt programa al.",
        value: "Onayladıktan sonra ekip bildirim alır, fazlar takvime işlenir, takip başlar.",
        actionLabel: "Bu Planla Programa Al",
      },
    ],
    href: "/dashboard/is-programi",
    target: "is-programi",
    icon: "◷",
    order: 6,
    placement: "right",
  },
  {
    key: "tahsilat",
    title: "Nakit akışını görünür yap",
    shortDescription: "İş bitti ama para kaldı mı, Metrix kaybettirmez.",
    wowCopy: "Geciken tahsilat kaybolmasın. Nakit akışı müşteri ve iş bazında görünür hale gelsin.",
    coachmarkTitle: "Tahsilatı takip et.",
    coachmarkCopy: "Vade, ödeme ve müşteri bakiyesi aynı akışta aksiyona dönüşsün.",
    pageGuide: {
      title: "Ödeme durumunu takip et.",
      promise: "Metrix iş bittikten sonra paranın nerede kaldığını görünür yapar.",
      why: "Tahsilat takip edilmezse karlı görünen iş nakit akışında yük haline gelir.",
      bullets: ["Müşteri seç", "Tahsilat kaydı gir", "Geciken vadeleri izle"],
      outcome: "Geciken tahsilat kaybolmaz; nakit akışı müşteri, iş ve vade bazında takip edilir.",
    },
    pageTourSteps: [
      {
        key: "tahsilat-header",
        target: "tahsilat-header",
        title: "Tahsilat ekranı nakit kontrolüdür.",
        copy: "Burası sadece para girişi değildir; atölyenin nakit akışını gerçek zamanlı takip ettiğin yerdir.",
        value: "Vade, ödeme ve cari bakiye aynı ekranda birleştiğinde hangi alacağın aksiyon beklediği netleşir.",
      },
      {
        key: "tahsilat-musteri-search",
        target: "tahsilat-musteri-search",
        title: "Önce müşteriyi doğru seç.",
        copy: "Müşteriyi doğru seçmek, ödemenin doğru cari hesaba bağlanmasını sağlar.",
        value: "Yanlış müşteri seçimi tahsilatı görünür yapmaz; doğru kart nakit hafızasını temiz tutar.",
      },
      {
        key: "tahsilat-musteri-option",
        target: "tahsilat-musteri-option",
        title: "Borçlu müşteriyi listeden aç.",
        copy: "Arama sonucundan müşteriyi seç; Metrix bu müşteriye ait açık işleri ve tahsilat hareketlerini getirir.",
        value: "Bu seçimden sonra ödeme planı, bakiye ve geçmiş tek müşteri üzerinde okunur.",
      },
      {
        key: "tahsilat-musteri-phone-status",
        target: "tahsilat-musteri-phone-status",
        title: "Telefon bilgisi tahsilat aksiyonudur.",
        copy: "Telefon kayıtlıysa Metrix tahsilat hatırlatmasını WhatsApp'a hazırlar.",
        value: "Numara eksikse takip yükü artar; kayıtlı telefon tahsilatı tek tıkla aksiyona çevirir.",
      },
      {
        key: "tahsilat-wa-message",
        target: "tahsilat-wa-message",
        title: "Hatırlatmayı WhatsApp'a taşı.",
        copy: "Müşteriye kısa ve net bir ödeme hatırlatması göndermek takip disiplinini yükseltir.",
        value: "Metrix burada agresif tahsilat değil, profesyonel ve kayıtlı takip dili kurar.",
      },
      {
        key: "tahsilat-job-select",
        target: "tahsilat-job-select",
        title: "Ödemeyi işe bağla.",
        copy: "İşi seçmek, tahsilatın hangi teklif ve uygulama için alındığını netleştirir.",
        value: "İş bağlantısı temiz olduğunda karlılık ve kalan bakiye daha doğru okunur.",
      },
      {
        key: "tahsilat-plan-panel",
        target: "tahsilat-plan-panel",
        title: "Ödeme planı gecikmeyi görünür yapar.",
        copy: "Vade ve taksit bilgisi, hangi alacağın bugün aksiyon beklediğini gösterir.",
        value: "Görünmeyen alacak, tahsil edilemeyen alacaktadır.",
      },
      {
        key: "tahsilat-installment-row",
        target: "tahsilat-installment-row",
        title: "Her satır bir tahsilat sinyalidir.",
        copy: "Taksit satırında tutar, vade ve gecikme bilgisini birlikte görürsün.",
        value: "Bu görünüm tahsilatı hafızadan çıkarıp operasyon listesine dönüştürür.",
      },
      {
        key: "tahsilat-installment-paid",
        target: "tahsilat-installment-paid",
        title: "Ödeme alındığında işaretle.",
        copy: "Bu aksiyon ödeme planını günceller ve tahsilat kaydı oluşturma akışını başlatır.",
        value: "İlk fazda koç sadece alanı gösterir; finansal kararı ve kaydı kullanıcı yapar.",
      },
      {
        key: "tahsilat-mobile-tab-tahsilat",
        target: "tahsilat-mobile-tab-tahsilat",
        title: "Tahsilat giriş alanına geç.",
        copy: "Mobilde manuel ödeme kaydı için Tahsilat sekmesini açarsın.",
        value: "Sekmeler sadece görünümü değiştirir; finansal kayıt kullanıcı onayı olmadan oluşmaz.",
      },
      {
        key: "tahsilat-tab-payment",
        target: "tahsilat-tab-payment",
        title: "Manuel tahsilat alanı burada.",
        copy: "Plan dışı veya genel ödeme geldiğinde tahsilatı bu panelden kaydedersin.",
        value: "Tutarı ve tarihi doğru girmek hem iş karlılığını hem cari dengeyi temiz tutar.",
      },
      {
        key: "tahsilat-amount-input",
        target: "tahsilat-amount-input",
        title: "Tahsil edilen tutarı gir.",
        copy: "Tutar alanı cari hesabın temel hareketidir. Rakam net olmalı.",
        value: "Yanlış tutar, kalan bakiye ve müşteri performansını yanlış gösterir.",
      },
      {
        key: "tahsilat-date-input",
        target: "tahsilat-date-input",
        title: "Tarihi doğru bırak.",
        copy: "Tahsilat tarihi nakit akışı raporlarını ve müşteri ödeme disiplinini etkiler.",
        value: "Doğru tarih, aylık finans görünümünü temiz tutar.",
      },
      {
        key: "tahsilat-save",
        target: "tahsilat-save",
        title: "Kaydı kullanıcı onaylar.",
        copy: "Metrix alanları gösterir; tahsilat kaydını sen bilinçli şekilde oluşturursun.",
        value: "Bu patch rehberlik yapar, finansal işlem davranışını değiştirmez.",
      },
      {
        key: "tahsilat-history",
        target: "tahsilat-history",
        title: "Tahsilat geçmişini oku.",
        copy: "Geçmiş hareketler müşterinin ödeme disiplinini ve açık bakiyesini gösterir.",
        value: "Yeni iş vermeden önce müşterinin tahsilat ritmini buradan anlarsın.",
      },
    ],
    href: "/dashboard/tahsilatlar",
    target: "tahsilat",
    icon: "₺",
    order: 7,
    placement: "right",
  },
];

export const onboardingTotalSteps = onboardingSteps.length;
