import {
  testMaterialGroupFixtures,
  testMaterialGroupKeysAreUniquePerGroup,
  testMaterialGroupSummariesUseUniqueAreaAndProductCounts,
  testEffectiveMaterialSelectionUsesPieceOverride,
  testEffectiveMaterialSelectionUsesProductDefault,
  testBuildCostPreviewAggregatesTotals,
  testBuildCostPreviewCalculatesDefaultWaste,
  testBuildCostPreviewForMultipleMaterialGroups,
  testBuildCostPreviewForSingleMaterialGroup,
  testBuildCostPreviewUsesPieceOverrideMaterial,
  testBuildLayoutPreviewAggregatesTotals,
  testBuildLayoutPreviewCalculatesRequiredWasteAndTotalArea,
  testBuildLayoutPreviewCreatesGroupsForDifferentMaterials,
  testBuildLayoutPreviewCreatesSingleGroupForSingleMaterial,
  testBuildLayoutPreviewMarksMissingMaterial,
  testBuildLayoutPreviewPreservesPieceMetadata,
  testBuildLayoutPreviewSendsPieceOverrideToDifferentGroup,
  testBuildPlateAssignmentPreviewAggregatesTotals,
  testBuildPlateAssignmentPreviewCreatesSingleVirtualPlate,
  testBuildPlateAssignmentPreviewCreatesTwoVirtualPlatesForLargeArea,
  testBuildPlateAssignmentPreviewMarksMissingMaterial,
  testBuildPlateAssignmentPreviewMarksOverflow,
  testBuildPlateAssignmentPreviewPreservesAssignedPieceMetadata,
  testBuildPlateAssignmentPreviewSendsPieceOverrideToDifferentGroup,
  testBuildJobV5PersistencePlanDoesNotDedupeSameMaterialAcrossProducts,
  testBuildJobV5PersistencePlanDoesNotPersistDerivedPreviewFields,
  testBuildJobV5PersistencePlanLeavesPieceOverrideNullWhenMissing,
  testBuildJobV5PersistencePlanMapsPieceOverrideMaterialSelection,
  testBuildJobV5PersistencePlanMapsProductDefaultMaterialSelection,
  testBuildJobV5PersistencePlanMapsSeriesToCollectionAndSlabPriceToUnitCost,
  testBuildJobV5PersistencePlanMapsSingleAreaProductPiece,
  testBuildJobV5PersistencePlanPreservesOriginalMaterialSelectionSnapshot,
  testBuildJobV5PersistencePlanReplacesUnsafeDraftIds,
  testBuildJobV5PersistencePlanRequiresAtolyeId,
  testBuildJobV5PersistencePlanRequiresTitle,
  testSaveJobV5DraftCreateDoesNotPartiallyWriteOutsideTransaction,
  testSaveJobV5DraftCreateUsesSingleTransactionAndSafeCreateOrder,
  testSaveJobV5DraftUpdateChecksOwnershipBeforeReplacingChildren,
  testSaveJobV5DraftUpdateRollsBackWhenOwnershipFails,
  testSaveJobV5DraftValidatesCustomerOwnership,
  testMapJobV5SaveErrorMapsRouteResponses,
  testParseSaveJobV5DraftRequestAcceptsCreatePayload,
  testParseSaveJobV5DraftRequestDerivesUpdateFromJobId,
  testParseSaveJobV5DraftRequestRejectsInvalidPayload,
  testSaveJobV5DraftClientMapsUnknownHttpErrorTo500,
  testSaveJobV5DraftClientNormalizesHttpErrors,
  testSaveJobV5DraftClientPostsTypedPayload,
  testSaveJobV5DraftClientRejectsInvalidSuccessResponse,
  testSaveJobV5DraftClientSendsJobIdForUpdate,
  testBuildPurchaseRequirementPreviewAggregatesTotals,
  testBuildPurchaseRequirementPreviewCreatesRequirementPerStockRequirement,
  testBuildPurchaseRequirementPreviewCreatesSingleRequirement,
  testBuildPurchaseRequirementPreviewDefaultsToPurchaseRequired,
  testBuildPurchaseRequirementPreviewTransfersPlateCount,
  testBuildPurchaseRequirementPreviewTransfersPurchaseArea,
  testBuildQuotePreviewCreatesSingleLineForSingleMaterial,
  testBuildQuotePreviewDoesNotCreateWasteLine,
  testBuildQuotePreviewMergesSameAreaProductMaterial,
  testBuildQuotePreviewSplitsPieceOverrideMaterial,
  testBuildQuotePreviewSplitsSameProductDifferentMaterials,
  testBuildQuotePreviewUsesDisplayNameHelper,
  testBuildStockRequirementPreviewAggregatesTotals,
  testBuildStockRequirementPreviewCreatesRequirementPerMaterialGroup,
  testBuildStockRequirementPreviewCreatesSingleRequirement,
  testBuildStockRequirementPreviewIncludesWasteAreaInTotal,
  testCalculateEstimatedPlateCountUsesDefaultPlateArea,
  testMaterialGroupIdIsDerivedFromEffectiveMaterial,
  testQuoteLinesCanSplitSameAreaProductByMaterialGroup,
  testWasteIsCostOnlyAndNotSeparateCustomerQuoteLine,
} from "./__tests__/material-groups.test";

const tests: Array<[string, () => void | Promise<void>]> = [
  ["material group fixtures", testMaterialGroupFixtures],
  ["material group unique keys", testMaterialGroupKeysAreUniquePerGroup],
  ["material group summary counts", testMaterialGroupSummariesUseUniqueAreaAndProductCounts],
  ["effective material uses product default", testEffectiveMaterialSelectionUsesProductDefault],
  ["effective material uses piece override", testEffectiveMaterialSelectionUsesPieceOverride],
  ["quote lines split by material group", testQuoteLinesCanSplitSameAreaProductByMaterialGroup],
  ["waste stays cost-only for quote", testWasteIsCostOnlyAndNotSeparateCustomerQuoteLine],
  ["material group id derives from effective material", testMaterialGroupIdIsDerivedFromEffectiveMaterial],
  ["cost preview single material group", testBuildCostPreviewForSingleMaterialGroup],
  ["cost preview multiple material groups", testBuildCostPreviewForMultipleMaterialGroups],
  ["cost preview piece override", testBuildCostPreviewUsesPieceOverrideMaterial],
  ["cost preview default waste", testBuildCostPreviewCalculatesDefaultWaste],
  ["cost preview totals aggregation", testBuildCostPreviewAggregatesTotals],
  ["quote preview single material line", testBuildQuotePreviewCreatesSingleLineForSingleMaterial],
  ["quote preview merges same material", testBuildQuotePreviewMergesSameAreaProductMaterial],
  ["quote preview splits different materials", testBuildQuotePreviewSplitsSameProductDifferentMaterials],
  ["quote preview splits piece override", testBuildQuotePreviewSplitsPieceOverrideMaterial],
  ["quote preview hides waste line", testBuildQuotePreviewDoesNotCreateWasteLine],
  ["quote preview display name", testBuildQuotePreviewUsesDisplayNameHelper],
  ["layout preview single material group", testBuildLayoutPreviewCreatesSingleGroupForSingleMaterial],
  ["layout preview different material groups", testBuildLayoutPreviewCreatesGroupsForDifferentMaterials],
  ["layout preview piece override group", testBuildLayoutPreviewSendsPieceOverrideToDifferentGroup],
  ["layout preview preserves metadata", testBuildLayoutPreviewPreservesPieceMetadata],
  ["layout preview area calculations", testBuildLayoutPreviewCalculatesRequiredWasteAndTotalArea],
  ["layout preview missing material status", testBuildLayoutPreviewMarksMissingMaterial],
  ["layout preview totals aggregation", testBuildLayoutPreviewAggregatesTotals],
  ["stock requirement single material", testBuildStockRequirementPreviewCreatesSingleRequirement],
  ["stock requirement multiple materials", testBuildStockRequirementPreviewCreatesRequirementPerMaterialGroup],
  ["stock requirement plate count", testCalculateEstimatedPlateCountUsesDefaultPlateArea],
  ["stock requirement includes waste area", testBuildStockRequirementPreviewIncludesWasteAreaInTotal],
  ["stock requirement totals aggregation", testBuildStockRequirementPreviewAggregatesTotals],
  ["purchase requirement single material", testBuildPurchaseRequirementPreviewCreatesSingleRequirement],
  ["purchase requirement multiple materials", testBuildPurchaseRequirementPreviewCreatesRequirementPerStockRequirement],
  ["purchase requirement plate transfer", testBuildPurchaseRequirementPreviewTransfersPlateCount],
  ["purchase requirement area transfer", testBuildPurchaseRequirementPreviewTransfersPurchaseArea],
  ["purchase requirement totals aggregation", testBuildPurchaseRequirementPreviewAggregatesTotals],
  ["purchase requirement default status", testBuildPurchaseRequirementPreviewDefaultsToPurchaseRequired],
  ["plate assignment single virtual plate", testBuildPlateAssignmentPreviewCreatesSingleVirtualPlate],
  ["plate assignment large area plates", testBuildPlateAssignmentPreviewCreatesTwoVirtualPlatesForLargeArea],
  ["plate assignment piece override group", testBuildPlateAssignmentPreviewSendsPieceOverrideToDifferentGroup],
  ["plate assignment preserves metadata", testBuildPlateAssignmentPreviewPreservesAssignedPieceMetadata],
  ["plate assignment overflow status", testBuildPlateAssignmentPreviewMarksOverflow],
  ["plate assignment missing material status", testBuildPlateAssignmentPreviewMarksMissingMaterial],
  ["plate assignment totals aggregation", testBuildPlateAssignmentPreviewAggregatesTotals],
  ["persistence plan single area product piece", testBuildJobV5PersistencePlanMapsSingleAreaProductPiece],
  ["persistence plan product default material", testBuildJobV5PersistencePlanMapsProductDefaultMaterialSelection],
  ["persistence plan piece override material", testBuildJobV5PersistencePlanMapsPieceOverrideMaterialSelection],
  ["persistence plan missing override null", testBuildJobV5PersistencePlanLeavesPieceOverrideNullWhenMissing],
  ["persistence plan no material dedupe", testBuildJobV5PersistencePlanDoesNotDedupeSameMaterialAcrossProducts],
  ["persistence plan material snapshot", testBuildJobV5PersistencePlanPreservesOriginalMaterialSelectionSnapshot],
  ["persistence plan material field mapping", testBuildJobV5PersistencePlanMapsSeriesToCollectionAndSlabPriceToUnitCost],
  ["persistence plan excludes derived previews", testBuildJobV5PersistencePlanDoesNotPersistDerivedPreviewFields],
  ["persistence plan requires title", testBuildJobV5PersistencePlanRequiresTitle],
  ["persistence plan requires atolyeId", testBuildJobV5PersistencePlanRequiresAtolyeId],
  ["persistence plan replaces unsafe draft ids", testBuildJobV5PersistencePlanReplacesUnsafeDraftIds],
  ["v5 save create transaction order", testSaveJobV5DraftCreateUsesSingleTransactionAndSafeCreateOrder],
  ["v5 save update ownership and replace", testSaveJobV5DraftUpdateChecksOwnershipBeforeReplacingChildren],
  ["v5 save update ownership rollback", testSaveJobV5DraftUpdateRollsBackWhenOwnershipFails],
  ["v5 save customer ownership", testSaveJobV5DraftValidatesCustomerOwnership],
  ["v5 save no partial writes outside transaction", testSaveJobV5DraftCreateDoesNotPartiallyWriteOutsideTransaction],
  ["v5 save route create payload validation", testParseSaveJobV5DraftRequestAcceptsCreatePayload],
  ["v5 save route update payload validation", testParseSaveJobV5DraftRequestDerivesUpdateFromJobId],
  ["v5 save route rejects invalid payload", testParseSaveJobV5DraftRequestRejectsInvalidPayload],
  ["v5 save route error mapping", testMapJobV5SaveErrorMapsRouteResponses],
  ["v5 save client posts typed payload", testSaveJobV5DraftClientPostsTypedPayload],
  ["v5 save client sends job id for update", testSaveJobV5DraftClientSendsJobIdForUpdate],
  ["v5 save client normalizes http errors", testSaveJobV5DraftClientNormalizesHttpErrors],
  ["v5 save client maps unknown http errors", testSaveJobV5DraftClientMapsUnknownHttpErrorTo500],
  ["v5 save client rejects invalid success response", testSaveJobV5DraftClientRejectsInvalidSuccessResponse],
];

async function main() {
  for (const [name, run] of tests) {
    await run();
    console.log(`ok - ${name}`);
  }

  console.log(`${tests.length} yeni-is-v5 tests passed`);
}

void main();
