import {
  testMaterialGroupFixtures,
  testMaterialGroupKeysAreUniquePerGroup,
  testMaterialGroupSummariesUseUniqueAreaAndProductCounts,
  testEffectiveMaterialSelectionUsesPieceOverride,
  testEffectiveMaterialSelectionUsesProductDefault,
  testBuildCostPreviewAggregatesTotals,
  testBuildCostPreviewCalculatesDefaultWaste,
  testBuildCostPreviewForMultipleMaterialGroups,
  testBuildCostPreviewForSingleMaterialGroup,
  testBuildCostPreviewUsesPieceOverrideMaterial,
  testBuildLayoutPreviewAggregatesTotals,
  testBuildLayoutPreviewCalculatesRequiredWasteAndTotalArea,
  testBuildLayoutPreviewCreatesGroupsForDifferentMaterials,
  testBuildLayoutPreviewCreatesSingleGroupForSingleMaterial,
  testBuildLayoutPreviewMarksMissingMaterial,
  testBuildLayoutPreviewPreservesPieceMetadata,
  testBuildLayoutPreviewSendsPieceOverrideToDifferentGroup,
  testBuildPlateAssignmentPreviewAggregatesTotals,
  testBuildPlateAssignmentPreviewCreatesSingleVirtualPlate,
  testBuildPlateAssignmentPreviewCreatesTwoVirtualPlatesForLargeArea,
  testBuildPlateAssignmentPreviewMarksMissingMaterial,
  testBuildPlateAssignmentPreviewMarksOverflow,
  testBuildPlateAssignmentPreviewPreservesAssignedPieceMetadata,
  testBuildPlateAssignmentPreviewSendsPieceOverrideToDifferentGroup,
  testBuildPurchaseRequirementPreviewAggregatesTotals,
  testBuildPurchaseRequirementPreviewCreatesRequirementPerStockRequirement,
  testBuildPurchaseRequirementPreviewCreatesSingleRequirement,
  testBuildPurchaseRequirementPreviewDefaultsToPurchaseRequired,
  testBuildPurchaseRequirementPreviewTransfersPlateCount,
  testBuildPurchaseRequirementPreviewTransfersPurchaseArea,
  testBuildQuotePreviewCreatesSingleLineForSingleMaterial,
  testBuildQuotePreviewDoesNotCreateWasteLine,
  testBuildQuotePreviewMergesSameAreaProductMaterial,
  testBuildQuotePreviewSplitsPieceOverrideMaterial,
  testBuildQuotePreviewSplitsSameProductDifferentMaterials,
  testBuildQuotePreviewUsesDisplayNameHelper,
  testBuildStockRequirementPreviewAggregatesTotals,
  testBuildStockRequirementPreviewCreatesRequirementPerMaterialGroup,
  testBuildStockRequirementPreviewCreatesSingleRequirement,
  testBuildStockRequirementPreviewIncludesWasteAreaInTotal,
  testCalculateEstimatedPlateCountUsesDefaultPlateArea,
  testMaterialGroupIdIsDerivedFromEffectiveMaterial,
  testQuoteLinesCanSplitSameAreaProductByMaterialGroup,
  testWasteIsCostOnlyAndNotSeparateCustomerQuoteLine,
} from "./__tests__/material-groups.test";

const tests: Array<[string, () => void]> = [
  ["material group fixtures", testMaterialGroupFixtures],
  ["material group unique keys", testMaterialGroupKeysAreUniquePerGroup],
  ["material group summary counts", testMaterialGroupSummariesUseUniqueAreaAndProductCounts],
  ["effective material uses product default", testEffectiveMaterialSelectionUsesProductDefault],
  ["effective material uses piece override", testEffectiveMaterialSelectionUsesPieceOverride],
  ["quote lines split by material group", testQuoteLinesCanSplitSameAreaProductByMaterialGroup],
  ["waste stays cost-only for quote", testWasteIsCostOnlyAndNotSeparateCustomerQuoteLine],
  ["material group id derives from effective material", testMaterialGroupIdIsDerivedFromEffectiveMaterial],
  ["cost preview single material group", testBuildCostPreviewForSingleMaterialGroup],
  ["cost preview multiple material groups", testBuildCostPreviewForMultipleMaterialGroups],
  ["cost preview piece override", testBuildCostPreviewUsesPieceOverrideMaterial],
  ["cost preview default waste", testBuildCostPreviewCalculatesDefaultWaste],
  ["cost preview totals aggregation", testBuildCostPreviewAggregatesTotals],
  ["quote preview single material line", testBuildQuotePreviewCreatesSingleLineForSingleMaterial],
  ["quote preview merges same material", testBuildQuotePreviewMergesSameAreaProductMaterial],
  ["quote preview splits different materials", testBuildQuotePreviewSplitsSameProductDifferentMaterials],
  ["quote preview splits piece override", testBuildQuotePreviewSplitsPieceOverrideMaterial],
  ["quote preview hides waste line", testBuildQuotePreviewDoesNotCreateWasteLine],
  ["quote preview display name", testBuildQuotePreviewUsesDisplayNameHelper],
  ["layout preview single material group", testBuildLayoutPreviewCreatesSingleGroupForSingleMaterial],
  ["layout preview different material groups", testBuildLayoutPreviewCreatesGroupsForDifferentMaterials],
  ["layout preview piece override group", testBuildLayoutPreviewSendsPieceOverrideToDifferentGroup],
  ["layout preview preserves metadata", testBuildLayoutPreviewPreservesPieceMetadata],
  ["layout preview area calculations", testBuildLayoutPreviewCalculatesRequiredWasteAndTotalArea],
  ["layout preview missing material status", testBuildLayoutPreviewMarksMissingMaterial],
  ["layout preview totals aggregation", testBuildLayoutPreviewAggregatesTotals],
  ["stock requirement single material", testBuildStockRequirementPreviewCreatesSingleRequirement],
  ["stock requirement multiple materials", testBuildStockRequirementPreviewCreatesRequirementPerMaterialGroup],
  ["stock requirement plate count", testCalculateEstimatedPlateCountUsesDefaultPlateArea],
  ["stock requirement includes waste area", testBuildStockRequirementPreviewIncludesWasteAreaInTotal],
  ["stock requirement totals aggregation", testBuildStockRequirementPreviewAggregatesTotals],
  ["purchase requirement single material", testBuildPurchaseRequirementPreviewCreatesSingleRequirement],
  ["purchase requirement multiple materials", testBuildPurchaseRequirementPreviewCreatesRequirementPerStockRequirement],
  ["purchase requirement plate transfer", testBuildPurchaseRequirementPreviewTransfersPlateCount],
  ["purchase requirement area transfer", testBuildPurchaseRequirementPreviewTransfersPurchaseArea],
  ["purchase requirement totals aggregation", testBuildPurchaseRequirementPreviewAggregatesTotals],
  ["purchase requirement default status", testBuildPurchaseRequirementPreviewDefaultsToPurchaseRequired],
  ["plate assignment single virtual plate", testBuildPlateAssignmentPreviewCreatesSingleVirtualPlate],
  ["plate assignment large area plates", testBuildPlateAssignmentPreviewCreatesTwoVirtualPlatesForLargeArea],
  ["plate assignment piece override group", testBuildPlateAssignmentPreviewSendsPieceOverrideToDifferentGroup],
  ["plate assignment preserves metadata", testBuildPlateAssignmentPreviewPreservesAssignedPieceMetadata],
  ["plate assignment overflow status", testBuildPlateAssignmentPreviewMarksOverflow],
  ["plate assignment missing material status", testBuildPlateAssignmentPreviewMarksMissingMaterial],
  ["plate assignment totals aggregation", testBuildPlateAssignmentPreviewAggregatesTotals],
];

for (const [name, run] of tests) {
  run();
  console.log(`ok - ${name}`);
}

console.log(`${tests.length} yeni-is-v5 tests passed`);
